FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

RUN dotnet dev-certs https
RUN dotnet dev-certs https --trust

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

COPY . .

RUN dotnet tool install --global dotnet-ef --version 5.0.17

CMD sh
